# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autcup.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!
import dbtest
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem

mydb = dbtest.MyDataBase()

class Ui_autMain(object):
    def setupUi(self, autMain):
        autMain.setObjectName("autMain")
        autMain.resize(800, 600)
        autMain.setMinimumSize(QtCore.QSize(800, 600))
        autMain.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(autMain)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, -10, 800, 600))
        self.stackedWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.stackedWidget.setMaximumSize(QtCore.QSize(800, 600))
        self.stackedWidget.setObjectName("stackedWidget")
        self.leaguePage = QtWidgets.QWidget()
        self.leaguePage.setObjectName("leaguePage")
        self.leagueLabel = QtWidgets.QLabel(self.leaguePage)
        self.leagueLabel.setGeometry(QtCore.QRect(340, 60, 111, 51))
        self.leagueLabel.setStyleSheet("font: 22pt \"Laksaman\";")
        self.leagueLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.leagueLabel.setObjectName("leagueLabel")
        self.label = QtWidgets.QLabel(self.leaguePage)
        self.label.setGeometry(QtCore.QRect(350, 110, 91, 41))
        self.label.setStyleSheet("color: rgb(0, 170, 255);\n"
"font: 63 20pt \"KacstBook\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.humanoidButton = QtWidgets.QPushButton(self.leaguePage)
        self.humanoidButton.setGeometry(QtCore.QRect(130, 190, 121, 51))
        self.humanoidButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.humanoidButton.setObjectName("humanoidButton")
        self.transporterButton = QtWidgets.QPushButton(self.leaguePage)
        self.transporterButton.setGeometry(QtCore.QRect(320, 190, 121, 51))
        self.transporterButton.setStyleSheet("font: 63 14pt \"KacstArt\";\n"
"")
        self.transporterButton.setObjectName("transporterButton")
        self.uavButton = QtWidgets.QPushButton(self.leaguePage)
        self.uavButton.setGeometry(QtCore.QRect(520, 190, 121, 51))
        self.uavButton.setStyleSheet("font: 63 14pt \"KacstArt\";\n"
"")
        self.uavButton.setObjectName("uavButton")
        self.deminerButton = QtWidgets.QPushButton(self.leaguePage)
        self.deminerButton.setGeometry(QtCore.QRect(230, 270, 121, 51))
        self.deminerButton.setStyleSheet("font: 63 14pt \"KacstArt\";\n"
"")
        self.deminerButton.setObjectName("deminerButton")
        self.atworkButton = QtWidgets.QPushButton(self.leaguePage)
        self.atworkButton.setGeometry(QtCore.QRect(420, 270, 121, 51))
        self.atworkButton.setStyleSheet("font: 63 14pt \"KacstArt\";\n"
"")
        self.atworkButton.setObjectName("atworkButton")
        self.juniorLeague = QtWidgets.QLabel(self.leaguePage)
        self.juniorLeague.setGeometry(QtCore.QRect(350, 370, 91, 41))
        self.juniorLeague.setStyleSheet("color: rgb(0, 170, 255);\n"
"font: 63 20pt \"KacstBook\";")
        self.juniorLeague.setAlignment(QtCore.Qt.AlignCenter)
        self.juniorLeague.setObjectName("juniorLeague")
        self.jhumanoidButton = QtWidgets.QPushButton(self.leaguePage)
        self.jhumanoidButton.setGeometry(QtCore.QRect(120, 440, 121, 51))
        self.jhumanoidButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.jhumanoidButton.setObjectName("jhumanoidButton")
        self.transporterAButton = QtWidgets.QPushButton(self.leaguePage)
        self.transporterAButton.setGeometry(QtCore.QRect(330, 440, 141, 51))
        self.transporterAButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.transporterAButton.setObjectName("transporterAButton")
        self.transpoterBButton = QtWidgets.QPushButton(self.leaguePage)
        self.transpoterBButton.setGeometry(QtCore.QRect(540, 440, 141, 51))
        self.transpoterBButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.transpoterBButton.setObjectName("transpoterBButton")
        self.stackedWidget.addWidget(self.leaguePage)
        self.humanoidPage = QtWidgets.QWidget()
        self.humanoidPage.setObjectName("humanoidPage")
        self.humanoidTitle = QtWidgets.QLabel(self.humanoidPage)
        self.humanoidTitle.setGeometry(QtCore.QRect(340, 30, 141, 51))
        self.humanoidTitle.setStyleSheet("font: 22pt \"Laksaman\";")
        self.humanoidTitle.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.humanoidTitle.setObjectName("humanoidTitle")
        self.humanoidTab = QtWidgets.QTabWidget(self.humanoidPage)
        self.humanoidTab.setGeometry(QtCore.QRect(30, 80, 741, 471))
        self.humanoidTab.setObjectName("humanoidTab")
        self.humanoidHomeTab = QtWidgets.QWidget()
        self.humanoidHomeTab.setEnabled(True)
        self.humanoidHomeTab.setObjectName("humanoidHomeTab")
        self.humInTeamFrame = QtWidgets.QFrame(self.humanoidHomeTab)
        self.humInTeamFrame.setGeometry(QtCore.QRect(30, 70, 301, 321))
        self.humInTeamFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.humInTeamFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.humInTeamFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.humInTeamFrame.setObjectName("humInTeamFrame")
        self.humInTeamName = QtWidgets.QLineEdit(self.humInTeamFrame)
        self.humInTeamName.setGeometry(QtCore.QRect(40, 50, 221, 41))
        self.humInTeamName.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.humInTeamName.setObjectName("humInTeamName")
        self.humInTeamDep = QtWidgets.QLineEdit(self.humInTeamFrame)
        self.humInTeamDep.setGeometry(QtCore.QRect(40, 130, 221, 41))
        self.humInTeamDep.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.humInTeamDep.setObjectName("humInTeamDep")
        self.humInTeamSubmitButton = QtWidgets.QPushButton(self.humInTeamFrame)
        self.humInTeamSubmitButton.setGeometry(QtCore.QRect(80, 220, 131, 41))
        self.humInTeamSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.humInTeamSubmitButton.setObjectName("humInTeamSubmitButton")
        self.humHomeButton = QtWidgets.QPushButton(self.humanoidHomeTab)
        self.humHomeButton.setGeometry(QtCore.QRect(310, 20, 131, 41))
        self.humHomeButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.humHomeButton.setObjectName("humHomeButton")
        self.humInRecFrame = QtWidgets.QFrame(self.humanoidHomeTab)
        self.humInRecFrame.setGeometry(QtCore.QRect(410, 70, 301, 321))
        self.humInRecFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.humInRecFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.humInRecFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.humInRecFrame.setObjectName("humInRecFrame")
        self.humInRecTeam = QtWidgets.QLineEdit(self.humInRecFrame)
        self.humInRecTeam.setGeometry(QtCore.QRect(40, 20, 221, 41))
        self.humInRecTeam.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.humInRecTeam.setObjectName("humInRecTeam")
        self.humInRecSubmitButton = QtWidgets.QPushButton(self.humInRecFrame)
        self.humInRecSubmitButton.setGeometry(QtCore.QRect(90, 260, 131, 41))
        self.humInRecSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.humInRecSubmitButton.setObjectName("humInRecSubmitButton")
        self.humRec1Spin = QtWidgets.QDoubleSpinBox(self.humInRecFrame)
        self.humRec1Spin.setGeometry(QtCore.QRect(140, 120, 81, 31))
        self.humRec1Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.humRec1Spin.setDecimals(2)
        self.humRec1Spin.setMaximum(999.99)
        self.humRec1Spin.setObjectName("humRec1Spin")
        self.humRec2Spin = QtWidgets.QDoubleSpinBox(self.humInRecFrame)
        self.humRec2Spin.setGeometry(QtCore.QRect(140, 160, 81, 31))
        self.humRec2Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.humRec2Spin.setMaximum(999.99)
        self.humRec2Spin.setObjectName("humRec2Spin")
        self.humRec3Spin = QtWidgets.QDoubleSpinBox(self.humInRecFrame)
        self.humRec3Spin.setGeometry(QtCore.QRect(140, 200, 81, 31))
        self.humRec3Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.humRec3Spin.setMaximum(999.99)
        self.humRec3Spin.setObjectName("humRec3Spin")
        self.humRec1Label = QtWidgets.QLabel(self.humInRecFrame)
        self.humRec1Label.setGeometry(QtCore.QRect(50, 130, 71, 21))
        self.humRec1Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.humRec1Label.setObjectName("humRec1Label")
        self.humRec2Label = QtWidgets.QLabel(self.humInRecFrame)
        self.humRec2Label.setGeometry(QtCore.QRect(50, 170, 71, 21))
        self.humRec2Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.humRec2Label.setObjectName("humRec2Label")
        self.humRec3Label = QtWidgets.QLabel(self.humInRecFrame)
        self.humRec3Label.setGeometry(QtCore.QRect(50, 210, 71, 21))
        self.humRec3Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.humRec3Label.setObjectName("humRec3Label")
        self.humInRecLevel = QtWidgets.QComboBox(self.humInRecFrame)
        self.humInRecLevel.setGeometry(QtCore.QRect(40, 66, 221, 41))
        self.humInRecLevel.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.humInRecLevel.setObjectName("humInRecLevel")
        self.humInRecLevel.addItem("")
        self.humInRecLevel.addItem("")
        self.humInRecLevel.addItem("")
        self.humanoidTab.addTab(self.humanoidHomeTab, "")
        self.humanoidTeamTab = QtWidgets.QWidget()
        self.humanoidTeamTab.setObjectName("humanoidTeamTab")
        self.humanoidTeamTable = QtWidgets.QTableWidget(self.humanoidTeamTab)
        self.humanoidTeamTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.humanoidTeamTable.setObjectName("humanoidTeamTable")
        self.humanoidTeamTable.setColumnCount(0)
        self.humanoidTeamTable.setRowCount(0)
        self.humanoidTab.addTab(self.humanoidTeamTab, "")
        self.humanoidPreTab = QtWidgets.QWidget()
        self.humanoidPreTab.setObjectName("humanoidPreTab")
        self.humanoidPreTable = QtWidgets.QTableWidget(self.humanoidPreTab)
        self.humanoidPreTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.humanoidPreTable.setObjectName("humanoidPreTable")
        self.humanoidPreTable.setColumnCount(0)
        self.humanoidPreTable.setRowCount(0)
        self.humanoidTab.addTab(self.humanoidPreTab, "")
        self.humanoidSemiTab = QtWidgets.QWidget()
        self.humanoidSemiTab.setObjectName("humanoidSemiTab")
        self.humanoidSemiTable = QtWidgets.QTableWidget(self.humanoidSemiTab)
        self.humanoidSemiTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.humanoidSemiTable.setObjectName("humanoidSemiTable")
        self.humanoidSemiTable.setColumnCount(0)
        self.humanoidSemiTable.setRowCount(0)
        self.humanoidTab.addTab(self.humanoidSemiTab, "")
        self.humanoidFinalTab = QtWidgets.QWidget()
        self.humanoidFinalTab.setObjectName("humanoidFinalTab")
        self.humanoidFinalTable = QtWidgets.QTableWidget(self.humanoidFinalTab)
        self.humanoidFinalTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.humanoidFinalTable.setObjectName("humanoidFinalTable")
        self.humanoidFinalTable.setColumnCount(0)
        self.humanoidFinalTable.setRowCount(0)
        self.humanoidTab.addTab(self.humanoidFinalTab, "")
        self.stackedWidget.addWidget(self.humanoidPage)
        self.transporterPage = QtWidgets.QWidget()
        self.transporterPage.setObjectName("transporterPage")
        self.transporterTitle = QtWidgets.QLabel(self.transporterPage)
        self.transporterTitle.setGeometry(QtCore.QRect(320, 30, 161, 51))
        self.transporterTitle.setStyleSheet("font: 22pt \"Laksaman\";")
        self.transporterTitle.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.transporterTitle.setObjectName("transporterTitle")
        self.transporterTab = QtWidgets.QTabWidget(self.transporterPage)
        self.transporterTab.setGeometry(QtCore.QRect(30, 90, 741, 471))
        self.transporterTab.setObjectName("transporterTab")
        self.transporterHomeTab = QtWidgets.QWidget()
        self.transporterHomeTab.setEnabled(True)
        self.transporterHomeTab.setObjectName("transporterHomeTab")
        self.transporterInRecFrame = QtWidgets.QFrame(self.transporterHomeTab)
        self.transporterInRecFrame.setGeometry(QtCore.QRect(410, 70, 301, 321))
        self.transporterInRecFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.transporterInRecFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transporterInRecFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transporterInRecFrame.setObjectName("transporterInRecFrame")
        self.transporterInRecTeam = QtWidgets.QLineEdit(self.transporterInRecFrame)
        self.transporterInRecTeam.setGeometry(QtCore.QRect(40, 20, 221, 41))
        self.transporterInRecTeam.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transporterInRecTeam.setObjectName("transporterInRecTeam")
        self.transporterInRecSubmitButton = QtWidgets.QPushButton(self.transporterInRecFrame)
        self.transporterInRecSubmitButton.setGeometry(QtCore.QRect(90, 270, 131, 41))
        self.transporterInRecSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.transporterInRecSubmitButton.setObjectName("transporterInRecSubmitButton")
        self.transporterRec1Spin = QtWidgets.QDoubleSpinBox(self.transporterInRecFrame)
        self.transporterRec1Spin.setGeometry(QtCore.QRect(140, 130, 81, 31))
        self.transporterRec1Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transporterRec1Spin.setMaximum(999.99)
        self.transporterRec1Spin.setObjectName("transporterRec1Spin")
        self.transporterRec2Spin = QtWidgets.QDoubleSpinBox(self.transporterInRecFrame)
        self.transporterRec2Spin.setGeometry(QtCore.QRect(140, 170, 81, 31))
        self.transporterRec2Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transporterRec2Spin.setMaximum(999.99)
        self.transporterRec2Spin.setObjectName("transporterRec2Spin")
        self.transporterRec3Spin = QtWidgets.QDoubleSpinBox(self.transporterInRecFrame)
        self.transporterRec3Spin.setGeometry(QtCore.QRect(140, 210, 81, 31))
        self.transporterRec3Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transporterRec3Spin.setMaximum(999.99)
        self.transporterRec3Spin.setObjectName("transporterRec3Spin")
        self.transporterRec1Label = QtWidgets.QLabel(self.transporterInRecFrame)
        self.transporterRec1Label.setGeometry(QtCore.QRect(50, 140, 71, 21))
        self.transporterRec1Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transporterRec1Label.setObjectName("transporterRec1Label")
        self.transporterRec2Label = QtWidgets.QLabel(self.transporterInRecFrame)
        self.transporterRec2Label.setGeometry(QtCore.QRect(50, 180, 71, 21))
        self.transporterRec2Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transporterRec2Label.setObjectName("transporterRec2Label")
        self.transporterRec3Label = QtWidgets.QLabel(self.transporterInRecFrame)
        self.transporterRec3Label.setGeometry(QtCore.QRect(50, 220, 71, 21))
        self.transporterRec3Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transporterRec3Label.setObjectName("transporterRec3Label")
        self.transporterInRecLevel = QtWidgets.QComboBox(self.transporterInRecFrame)
        self.transporterInRecLevel.setGeometry(QtCore.QRect(40, 70, 221, 41))
        self.transporterInRecLevel.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transporterInRecLevel.setObjectName("transporterInRecLevel")
        self.transporterInRecLevel.addItem("")
        self.transporterInRecLevel.addItem("")
        self.transporterInRecLevel.addItem("")
        self.transporterHomeButton = QtWidgets.QPushButton(self.transporterHomeTab)
        self.transporterHomeButton.setGeometry(QtCore.QRect(310, 20, 131, 41))
        self.transporterHomeButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.transporterHomeButton.setObjectName("transporterHomeButton")
        self.transporterInTeamFrame = QtWidgets.QFrame(self.transporterHomeTab)
        self.transporterInTeamFrame.setGeometry(QtCore.QRect(30, 70, 301, 321))
        self.transporterInTeamFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.transporterInTeamFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transporterInTeamFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transporterInTeamFrame.setObjectName("transporterInTeamFrame")
        self.transporterInTeamName = QtWidgets.QLineEdit(self.transporterInTeamFrame)
        self.transporterInTeamName.setGeometry(QtCore.QRect(40, 50, 221, 41))
        self.transporterInTeamName.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transporterInTeamName.setObjectName("transporterInTeamName")
        self.transporterInTeamDep = QtWidgets.QLineEdit(self.transporterInTeamFrame)
        self.transporterInTeamDep.setGeometry(QtCore.QRect(40, 130, 221, 41))
        self.transporterInTeamDep.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transporterInTeamDep.setObjectName("transporterInTeamDep")
        self.transporterInTeamSubmitButton = QtWidgets.QPushButton(self.transporterInTeamFrame)
        self.transporterInTeamSubmitButton.setGeometry(QtCore.QRect(80, 220, 131, 41))
        self.transporterInTeamSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.transporterInTeamSubmitButton.setObjectName("transporterInTeamSubmitButton")
        self.transporterTab.addTab(self.transporterHomeTab, "")
        self.transporterTeamTab = QtWidgets.QWidget()
        self.transporterTeamTab.setObjectName("transporterTeamTab")
        self.transporterTeamTable = QtWidgets.QTableWidget(self.transporterTeamTab)
        self.transporterTeamTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.transporterTeamTable.setObjectName("transporterTeamTable")
        self.transporterTeamTable.setColumnCount(0)
        self.transporterTeamTable.setRowCount(0)
        self.transporterTab.addTab(self.transporterTeamTab, "")
        self.transporterPreTab = QtWidgets.QWidget()
        self.transporterPreTab.setObjectName("transporterPreTab")
        self.transporterPreTable = QtWidgets.QTableWidget(self.transporterPreTab)
        self.transporterPreTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.transporterPreTable.setObjectName("transporterPreTable")
        self.transporterPreTable.setColumnCount(0)
        self.transporterPreTable.setRowCount(0)
        self.transporterTab.addTab(self.transporterPreTab, "")
        self.transporterSemiTab = QtWidgets.QWidget()
        self.transporterSemiTab.setObjectName("transporterSemiTab")
        self.transporterSemiTable = QtWidgets.QTableWidget(self.transporterSemiTab)
        self.transporterSemiTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.transporterSemiTable.setObjectName("transporterSemiTable")
        self.transporterSemiTable.setColumnCount(0)
        self.transporterSemiTable.setRowCount(0)
        self.transporterTab.addTab(self.transporterSemiTab, "")
        self.transporterFinalTab = QtWidgets.QWidget()
        self.transporterFinalTab.setObjectName("transporterFinalTab")
        self.transporterFinalTable = QtWidgets.QTableWidget(self.transporterFinalTab)
        self.transporterFinalTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.transporterFinalTable.setObjectName("transporterFinalTable")
        self.transporterFinalTable.setColumnCount(0)
        self.transporterFinalTable.setRowCount(0)
        self.transporterTab.addTab(self.transporterFinalTab, "")
        self.stackedWidget.addWidget(self.transporterPage)
        self.uavPage = QtWidgets.QWidget()
        self.uavPage.setObjectName("uavPage")
        self.uavTitle = QtWidgets.QLabel(self.uavPage)
        self.uavTitle.setGeometry(QtCore.QRect(370, 30, 141, 51))
        self.uavTitle.setStyleSheet("font: 22pt \"Laksaman\";")
        self.uavTitle.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.uavTitle.setObjectName("uavTitle")
        self.uavTab = QtWidgets.QTabWidget(self.uavPage)
        self.uavTab.setGeometry(QtCore.QRect(30, 90, 741, 471))
        self.uavTab.setObjectName("uavTab")
        self.uavHomeTab = QtWidgets.QWidget()
        self.uavHomeTab.setEnabled(True)
        self.uavHomeTab.setObjectName("uavHomeTab")
        self.uavHomeButton = QtWidgets.QPushButton(self.uavHomeTab)
        self.uavHomeButton.setGeometry(QtCore.QRect(310, 20, 131, 41))
        self.uavHomeButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.uavHomeButton.setObjectName("uavHomeButton")
        self.uavInTeamFrame = QtWidgets.QFrame(self.uavHomeTab)
        self.uavInTeamFrame.setGeometry(QtCore.QRect(30, 70, 301, 321))
        self.uavInTeamFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.uavInTeamFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.uavInTeamFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.uavInTeamFrame.setObjectName("uavInTeamFrame")
        self.uavInTeamName = QtWidgets.QLineEdit(self.uavInTeamFrame)
        self.uavInTeamName.setGeometry(QtCore.QRect(40, 50, 221, 41))
        self.uavInTeamName.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.uavInTeamName.setObjectName("uavInTeamName")
        self.uavInTeamDep = QtWidgets.QLineEdit(self.uavInTeamFrame)
        self.uavInTeamDep.setGeometry(QtCore.QRect(40, 130, 221, 41))
        self.uavInTeamDep.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.uavInTeamDep.setObjectName("uavInTeamDep")
        self.uavInTeamSubmitButton = QtWidgets.QPushButton(self.uavInTeamFrame)
        self.uavInTeamSubmitButton.setGeometry(QtCore.QRect(80, 220, 131, 41))
        self.uavInTeamSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.uavInTeamSubmitButton.setObjectName("uavInTeamSubmitButton")
        self.uavInRecFrame = QtWidgets.QFrame(self.uavHomeTab)
        self.uavInRecFrame.setGeometry(QtCore.QRect(410, 70, 301, 321))
        self.uavInRecFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.uavInRecFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.uavInRecFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.uavInRecFrame.setObjectName("uavInRecFrame")
        self.uavInRecTeam = QtWidgets.QLineEdit(self.uavInRecFrame)
        self.uavInRecTeam.setGeometry(QtCore.QRect(40, 20, 221, 41))
        self.uavInRecTeam.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.uavInRecTeam.setObjectName("uavInRecTeam")
        self.uavInRecSubmitButton = QtWidgets.QPushButton(self.uavInRecFrame)
        self.uavInRecSubmitButton.setGeometry(QtCore.QRect(90, 260, 131, 41))
        self.uavInRecSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.uavInRecSubmitButton.setObjectName("uavInRecSubmitButton")
        self.uavRec1Spin = QtWidgets.QDoubleSpinBox(self.uavInRecFrame)
        self.uavRec1Spin.setGeometry(QtCore.QRect(140, 130, 81, 31))
        self.uavRec1Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.uavRec1Spin.setMaximum(999.99)
        self.uavRec1Spin.setObjectName("uavRec1Spin")
        self.uavRec2Spin = QtWidgets.QDoubleSpinBox(self.uavInRecFrame)
        self.uavRec2Spin.setGeometry(QtCore.QRect(140, 170, 81, 31))
        self.uavRec2Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.uavRec2Spin.setMaximum(999.99)
        self.uavRec2Spin.setObjectName("uavRec2Spin")
        self.uavRec3Spin = QtWidgets.QDoubleSpinBox(self.uavInRecFrame)
        self.uavRec3Spin.setGeometry(QtCore.QRect(140, 210, 81, 31))
        self.uavRec3Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.uavRec3Spin.setMaximum(999.99)
        self.uavRec3Spin.setObjectName("uavRec3Spin")
        self.uavRec1Label = QtWidgets.QLabel(self.uavInRecFrame)
        self.uavRec1Label.setGeometry(QtCore.QRect(50, 140, 71, 21))
        self.uavRec1Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.uavRec1Label.setObjectName("uavRec1Label")
        self.uavRec2Label = QtWidgets.QLabel(self.uavInRecFrame)
        self.uavRec2Label.setGeometry(QtCore.QRect(50, 180, 71, 21))
        self.uavRec2Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.uavRec2Label.setObjectName("uavRec2Label")
        self.uavRec3Label = QtWidgets.QLabel(self.uavInRecFrame)
        self.uavRec3Label.setGeometry(QtCore.QRect(50, 220, 71, 21))
        self.uavRec3Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.uavRec3Label.setObjectName("uavRec3Label")
        self.uavInRecLevel = QtWidgets.QComboBox(self.uavInRecFrame)
        self.uavInRecLevel.setGeometry(QtCore.QRect(40, 70, 221, 41))
        self.uavInRecLevel.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.uavInRecLevel.setObjectName("uavInRecLevel")
        self.uavInRecLevel.addItem("")
        self.uavInRecLevel.addItem("")
        self.uavInRecLevel.addItem("")
        self.uavTab.addTab(self.uavHomeTab, "")
        self.uavTeamTab = QtWidgets.QWidget()
        self.uavTeamTab.setObjectName("uavTeamTab")
        self.uavTeamTable = QtWidgets.QTableWidget(self.uavTeamTab)
        self.uavTeamTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.uavTeamTable.setObjectName("uavTeamTable")
        self.uavTeamTable.setColumnCount(0)
        self.uavTeamTable.setRowCount(0)
        self.uavTab.addTab(self.uavTeamTab, "")
        self.uavPreTab = QtWidgets.QWidget()
        self.uavPreTab.setObjectName("uavPreTab")
        self.uavPreTable = QtWidgets.QTableWidget(self.uavPreTab)
        self.uavPreTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.uavPreTable.setObjectName("uavPreTable")
        self.uavPreTable.setColumnCount(0)
        self.uavPreTable.setRowCount(0)
        self.uavTab.addTab(self.uavPreTab, "")
        self.uavSemiTab = QtWidgets.QWidget()
        self.uavSemiTab.setObjectName("uavSemiTab")
        self.uavSemiTable = QtWidgets.QTableWidget(self.uavSemiTab)
        self.uavSemiTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.uavSemiTable.setObjectName("uavSemiTable")
        self.uavSemiTable.setColumnCount(0)
        self.uavSemiTable.setRowCount(0)
        self.uavTab.addTab(self.uavSemiTab, "")
        self.uavFinalTab = QtWidgets.QWidget()
        self.uavFinalTab.setObjectName("uavFinalTab")
        self.uavFinalTable = QtWidgets.QTableWidget(self.uavFinalTab)
        self.uavFinalTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.uavFinalTable.setObjectName("uavFinalTable")
        self.uavFinalTable.setColumnCount(0)
        self.uavFinalTable.setRowCount(0)
        self.uavTab.addTab(self.uavFinalTab, "")
        self.stackedWidget.addWidget(self.uavPage)
        self.deminerPage = QtWidgets.QWidget()
        self.deminerPage.setObjectName("deminerPage")
        self.deminerTitle = QtWidgets.QLabel(self.deminerPage)
        self.deminerTitle.setGeometry(QtCore.QRect(340, 30, 121, 51))
        self.deminerTitle.setStyleSheet("font: 22pt \"Laksaman\";")
        self.deminerTitle.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.deminerTitle.setObjectName("deminerTitle")
        self.deminerTab = QtWidgets.QTabWidget(self.deminerPage)
        self.deminerTab.setGeometry(QtCore.QRect(30, 90, 741, 471))
        self.deminerTab.setObjectName("deminerTab")
        self.deminerHomeTab = QtWidgets.QWidget()
        self.deminerHomeTab.setEnabled(True)
        self.deminerHomeTab.setObjectName("deminerHomeTab")
        self.deminerInTeamFrame = QtWidgets.QFrame(self.deminerHomeTab)
        self.deminerInTeamFrame.setGeometry(QtCore.QRect(20, 70, 301, 321))
        self.deminerInTeamFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.deminerInTeamFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.deminerInTeamFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.deminerInTeamFrame.setObjectName("deminerInTeamFrame")
        self.deminerInTeamName = QtWidgets.QLineEdit(self.deminerInTeamFrame)
        self.deminerInTeamName.setGeometry(QtCore.QRect(40, 50, 221, 41))
        self.deminerInTeamName.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.deminerInTeamName.setObjectName("deminerInTeamName")
        self.deminerInTeamDep = QtWidgets.QLineEdit(self.deminerInTeamFrame)
        self.deminerInTeamDep.setGeometry(QtCore.QRect(40, 130, 221, 41))
        self.deminerInTeamDep.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.deminerInTeamDep.setObjectName("deminerInTeamDep")
        self.deminerInTeamSubmitButton = QtWidgets.QPushButton(self.deminerInTeamFrame)
        self.deminerInTeamSubmitButton.setGeometry(QtCore.QRect(80, 220, 131, 41))
        self.deminerInTeamSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.deminerInTeamSubmitButton.setObjectName("deminerInTeamSubmitButton")
        self.deminerInRecFrame = QtWidgets.QFrame(self.deminerHomeTab)
        self.deminerInRecFrame.setGeometry(QtCore.QRect(400, 70, 301, 321))
        self.deminerInRecFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.deminerInRecFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.deminerInRecFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.deminerInRecFrame.setObjectName("deminerInRecFrame")
        self.deminerInRecTeam = QtWidgets.QLineEdit(self.deminerInRecFrame)
        self.deminerInRecTeam.setGeometry(QtCore.QRect(40, 20, 221, 41))
        self.deminerInRecTeam.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.deminerInRecTeam.setObjectName("deminerInRecTeam")
        self.deminerInRecSubmitButton = QtWidgets.QPushButton(self.deminerInRecFrame)
        self.deminerInRecSubmitButton.setGeometry(QtCore.QRect(90, 260, 131, 41))
        self.deminerInRecSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.deminerInRecSubmitButton.setObjectName("deminerInRecSubmitButton")
        self.deminerRec1Spin = QtWidgets.QDoubleSpinBox(self.deminerInRecFrame)
        self.deminerRec1Spin.setGeometry(QtCore.QRect(140, 130, 81, 31))
        self.deminerRec1Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.deminerRec1Spin.setMaximum(999.99)
        self.deminerRec1Spin.setObjectName("deminerRec1Spin")
        self.deminerRec2Spin = QtWidgets.QDoubleSpinBox(self.deminerInRecFrame)
        self.deminerRec2Spin.setGeometry(QtCore.QRect(140, 170, 81, 31))
        self.deminerRec2Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.deminerRec2Spin.setMaximum(999.99)
        self.deminerRec2Spin.setObjectName("deminerRec2Spin")
        self.deminerRec3Spin = QtWidgets.QDoubleSpinBox(self.deminerInRecFrame)
        self.deminerRec3Spin.setGeometry(QtCore.QRect(140, 210, 81, 31))
        self.deminerRec3Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.deminerRec3Spin.setMaximum(999.99)
        self.deminerRec3Spin.setObjectName("deminerRec3Spin")
        self.deminerRec1Label = QtWidgets.QLabel(self.deminerInRecFrame)
        self.deminerRec1Label.setGeometry(QtCore.QRect(50, 140, 71, 21))
        self.deminerRec1Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.deminerRec1Label.setObjectName("deminerRec1Label")
        self.deminerRec2Label = QtWidgets.QLabel(self.deminerInRecFrame)
        self.deminerRec2Label.setGeometry(QtCore.QRect(50, 180, 71, 21))
        self.deminerRec2Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.deminerRec2Label.setObjectName("deminerRec2Label")
        self.deminerRec3Label = QtWidgets.QLabel(self.deminerInRecFrame)
        self.deminerRec3Label.setGeometry(QtCore.QRect(50, 220, 71, 21))
        self.deminerRec3Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.deminerRec3Label.setObjectName("deminerRec3Label")
        self.deminerInRecLevel = QtWidgets.QComboBox(self.deminerInRecFrame)
        self.deminerInRecLevel.setGeometry(QtCore.QRect(40, 70, 221, 41))
        self.deminerInRecLevel.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.deminerInRecLevel.setObjectName("deminerInRecLevel")
        self.deminerInRecLevel.addItem("")
        self.deminerInRecLevel.addItem("")
        self.deminerInRecLevel.addItem("")
        self.deminerHomeButton = QtWidgets.QPushButton(self.deminerHomeTab)
        self.deminerHomeButton.setGeometry(QtCore.QRect(300, 20, 131, 41))
        self.deminerHomeButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.deminerHomeButton.setObjectName("deminerHomeButton")
        self.deminerTab.addTab(self.deminerHomeTab, "")
        self.deminerTeamTab = QtWidgets.QWidget()
        self.deminerTeamTab.setObjectName("deminerTeamTab")
        self.deminerTeamTable = QtWidgets.QTableWidget(self.deminerTeamTab)
        self.deminerTeamTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.deminerTeamTable.setObjectName("deminerTeamTable")
        self.deminerTeamTable.setColumnCount(0)
        self.deminerTeamTable.setRowCount(0)
        self.deminerTab.addTab(self.deminerTeamTab, "")
        self.deminerPreTab = QtWidgets.QWidget()
        self.deminerPreTab.setObjectName("deminerPreTab")
        self.deminerPreTable = QtWidgets.QTableWidget(self.deminerPreTab)
        self.deminerPreTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.deminerPreTable.setObjectName("deminerPreTable")
        self.deminerPreTable.setColumnCount(0)
        self.deminerPreTable.setRowCount(0)
        self.deminerTab.addTab(self.deminerPreTab, "")
        self.deminerSemiTab = QtWidgets.QWidget()
        self.deminerSemiTab.setObjectName("deminerSemiTab")
        self.deminerSemiTable = QtWidgets.QTableWidget(self.deminerSemiTab)
        self.deminerSemiTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.deminerSemiTable.setObjectName("deminerSemiTable")
        self.deminerSemiTable.setColumnCount(0)
        self.deminerSemiTable.setRowCount(0)
        self.deminerTab.addTab(self.deminerSemiTab, "")
        self.deminerFinalTab = QtWidgets.QWidget()
        self.deminerFinalTab.setObjectName("deminerFinalTab")
        self.deminerFinalTable = QtWidgets.QTableWidget(self.deminerFinalTab)
        self.deminerFinalTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.deminerFinalTable.setObjectName("deminerFinalTable")
        self.deminerFinalTable.setColumnCount(0)
        self.deminerFinalTable.setRowCount(0)
        self.deminerTab.addTab(self.deminerFinalTab, "")
        self.stackedWidget.addWidget(self.deminerPage)
        self.atworkPage = QtWidgets.QWidget()
        self.atworkPage.setObjectName("atworkPage")
        self.atworkTab = QtWidgets.QTabWidget(self.atworkPage)
        self.atworkTab.setGeometry(QtCore.QRect(30, 90, 741, 471))
        self.atworkTab.setObjectName("atworkTab")
        self.atworkHomeTab = QtWidgets.QWidget()
        self.atworkHomeTab.setEnabled(True)
        self.atworkHomeTab.setObjectName("atworkHomeTab")
        self.atworkInTeamFrame = QtWidgets.QFrame(self.atworkHomeTab)
        self.atworkInTeamFrame.setGeometry(QtCore.QRect(30, 70, 301, 321))
        self.atworkInTeamFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.atworkInTeamFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.atworkInTeamFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.atworkInTeamFrame.setObjectName("atworkInTeamFrame")
        self.atworkInTeamName = QtWidgets.QLineEdit(self.atworkInTeamFrame)
        self.atworkInTeamName.setGeometry(QtCore.QRect(40, 50, 221, 41))
        self.atworkInTeamName.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.atworkInTeamName.setObjectName("atworkInTeamName")
        self.atworkInTeamDep = QtWidgets.QLineEdit(self.atworkInTeamFrame)
        self.atworkInTeamDep.setGeometry(QtCore.QRect(40, 130, 221, 41))
        self.atworkInTeamDep.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.atworkInTeamDep.setObjectName("atworkInTeamDep")
        self.atworkInTeamSubmitButton = QtWidgets.QPushButton(self.atworkInTeamFrame)
        self.atworkInTeamSubmitButton.setGeometry(QtCore.QRect(80, 220, 131, 41))
        self.atworkInTeamSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.atworkInTeamSubmitButton.setObjectName("atworkInTeamSubmitButton")
        self.atworkInRecFrame = QtWidgets.QFrame(self.atworkHomeTab)
        self.atworkInRecFrame.setGeometry(QtCore.QRect(410, 70, 301, 321))
        self.atworkInRecFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.atworkInRecFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.atworkInRecFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.atworkInRecFrame.setObjectName("atworkInRecFrame")
        self.atworkInRecTeam = QtWidgets.QLineEdit(self.atworkInRecFrame)
        self.atworkInRecTeam.setGeometry(QtCore.QRect(40, 20, 221, 41))
        self.atworkInRecTeam.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.atworkInRecTeam.setObjectName("atworkInRecTeam")
        self.atworkInRecSubmitButton = QtWidgets.QPushButton(self.atworkInRecFrame)
        self.atworkInRecSubmitButton.setGeometry(QtCore.QRect(90, 260, 131, 41))
        self.atworkInRecSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.atworkInRecSubmitButton.setObjectName("atworkInRecSubmitButton")
        self.atworkRec1Spin = QtWidgets.QDoubleSpinBox(self.atworkInRecFrame)
        self.atworkRec1Spin.setGeometry(QtCore.QRect(140, 130, 81, 31))
        self.atworkRec1Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.atworkRec1Spin.setMaximum(999.99)
        self.atworkRec1Spin.setObjectName("atworkRec1Spin")
        self.atworkRec2Spin = QtWidgets.QDoubleSpinBox(self.atworkInRecFrame)
        self.atworkRec2Spin.setGeometry(QtCore.QRect(140, 170, 81, 31))
        self.atworkRec2Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.atworkRec2Spin.setMaximum(999.99)
        self.atworkRec2Spin.setObjectName("atworkRec2Spin")
        self.atworkRec3Spin = QtWidgets.QDoubleSpinBox(self.atworkInRecFrame)
        self.atworkRec3Spin.setGeometry(QtCore.QRect(140, 210, 81, 31))
        self.atworkRec3Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.atworkRec3Spin.setMaximum(999.99)
        self.atworkRec3Spin.setObjectName("atworkRec3Spin")
        self.atworkRec1Label = QtWidgets.QLabel(self.atworkInRecFrame)
        self.atworkRec1Label.setGeometry(QtCore.QRect(50, 140, 71, 21))
        self.atworkRec1Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.atworkRec1Label.setObjectName("atworkRec1Label")
        self.atworkRec2Label = QtWidgets.QLabel(self.atworkInRecFrame)
        self.atworkRec2Label.setGeometry(QtCore.QRect(50, 180, 71, 21))
        self.atworkRec2Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.atworkRec2Label.setObjectName("atworkRec2Label")
        self.atworkRec3Label = QtWidgets.QLabel(self.atworkInRecFrame)
        self.atworkRec3Label.setGeometry(QtCore.QRect(50, 220, 71, 21))
        self.atworkRec3Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.atworkRec3Label.setObjectName("atworkRec3Label")
        self.atworkInRecLevel = QtWidgets.QComboBox(self.atworkInRecFrame)
        self.atworkInRecLevel.setGeometry(QtCore.QRect(40, 70, 221, 41))
        self.atworkInRecLevel.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.atworkInRecLevel.setObjectName("atworkInRecLevel")
        self.atworkInRecLevel.addItem("")
        self.atworkInRecLevel.addItem("")
        self.atworkInRecLevel.addItem("")
        self.atworkHomeButto = QtWidgets.QPushButton(self.atworkHomeTab)
        self.atworkHomeButto.setGeometry(QtCore.QRect(310, 20, 131, 41))
        self.atworkHomeButto.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.atworkHomeButto.setObjectName("atworkHomeButto")
        self.atworkTab.addTab(self.atworkHomeTab, "")
        self.atworkTeamTab = QtWidgets.QWidget()
        self.atworkTeamTab.setObjectName("atworkTeamTab")
        self.atworkTeamTable = QtWidgets.QTableWidget(self.atworkTeamTab)
        self.atworkTeamTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.atworkTeamTable.setObjectName("atworkTeamTable")
        self.atworkTeamTable.setColumnCount(0)
        self.atworkTeamTable.setRowCount(0)
        self.atworkTab.addTab(self.atworkTeamTab, "")
        self.atworkPreTab = QtWidgets.QWidget()
        self.atworkPreTab.setObjectName("atworkPreTab")
        self.atworkPreTable = QtWidgets.QTableWidget(self.atworkPreTab)
        self.atworkPreTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.atworkPreTable.setObjectName("atworkPreTable")
        self.atworkPreTable.setColumnCount(0)
        self.atworkPreTable.setRowCount(0)
        self.atworkTab.addTab(self.atworkPreTab, "")
        self.atworkSemiTab = QtWidgets.QWidget()
        self.atworkSemiTab.setObjectName("atworkSemiTab")
        self.atworkSemiTable = QtWidgets.QTableWidget(self.atworkSemiTab)
        self.atworkSemiTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.atworkSemiTable.setObjectName("atworkSemiTable")
        self.atworkSemiTable.setColumnCount(0)
        self.atworkSemiTable.setRowCount(0)
        self.atworkTab.addTab(self.atworkSemiTab, "")
        self.atworkFinalTab = QtWidgets.QWidget()
        self.atworkFinalTab.setObjectName("atworkFinalTab")
        self.atworkFinalTable = QtWidgets.QTableWidget(self.atworkFinalTab)
        self.atworkFinalTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.atworkFinalTable.setObjectName("atworkFinalTable")
        self.atworkFinalTable.setColumnCount(0)
        self.atworkFinalTable.setRowCount(0)
        self.atworkTab.addTab(self.atworkFinalTab, "")
        self.atWorkTitle = QtWidgets.QLabel(self.atworkPage)
        self.atWorkTitle.setGeometry(QtCore.QRect(350, 30, 121, 51))
        self.atWorkTitle.setStyleSheet("font: 22pt \"Laksaman\";")
        self.atWorkTitle.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.atWorkTitle.setObjectName("atWorkTitle")
        self.stackedWidget.addWidget(self.atworkPage)
        self.jhumanoidPage = QtWidgets.QWidget()
        self.jhumanoidPage.setObjectName("jhumanoidPage")
        self.jhumanoidTab = QtWidgets.QTabWidget(self.jhumanoidPage)
        self.jhumanoidTab.setGeometry(QtCore.QRect(30, 90, 741, 471))
        self.jhumanoidTab.setObjectName("jhumanoidTab")
        self.jhumanoidHomeTab = QtWidgets.QWidget()
        self.jhumanoidHomeTab.setEnabled(True)
        self.jhumanoidHomeTab.setObjectName("jhumanoidHomeTab")
        self.jhumInTeamFrame = QtWidgets.QFrame(self.jhumanoidHomeTab)
        self.jhumInTeamFrame.setGeometry(QtCore.QRect(30, 70, 301, 321))
        self.jhumInTeamFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.jhumInTeamFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.jhumInTeamFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.jhumInTeamFrame.setObjectName("jhumInTeamFrame")
        self.jhumInTeamName = QtWidgets.QLineEdit(self.jhumInTeamFrame)
        self.jhumInTeamName.setGeometry(QtCore.QRect(40, 50, 221, 41))
        self.jhumInTeamName.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.jhumInTeamName.setObjectName("jhumInTeamName")
        self.jhumInTeamDep = QtWidgets.QLineEdit(self.jhumInTeamFrame)
        self.jhumInTeamDep.setGeometry(QtCore.QRect(40, 130, 221, 41))
        self.jhumInTeamDep.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.jhumInTeamDep.setObjectName("jhumInTeamDep")
        self.jhumInTeamSubmitButton = QtWidgets.QPushButton(self.jhumInTeamFrame)
        self.jhumInTeamSubmitButton.setGeometry(QtCore.QRect(80, 220, 131, 41))
        self.jhumInTeamSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.jhumInTeamSubmitButton.setObjectName("jhumInTeamSubmitButton")
        self.jhumInRecFrame = QtWidgets.QFrame(self.jhumanoidHomeTab)
        self.jhumInRecFrame.setGeometry(QtCore.QRect(410, 70, 301, 321))
        self.jhumInRecFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.jhumInRecFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.jhumInRecFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.jhumInRecFrame.setObjectName("jhumInRecFrame")
        self.jhumInRecTeam = QtWidgets.QLineEdit(self.jhumInRecFrame)
        self.jhumInRecTeam.setGeometry(QtCore.QRect(40, 20, 221, 41))
        self.jhumInRecTeam.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.jhumInRecTeam.setObjectName("jhumInRecTeam")
        self.jhumInRecSubmitButton = QtWidgets.QPushButton(self.jhumInRecFrame)
        self.jhumInRecSubmitButton.setGeometry(QtCore.QRect(90, 270, 131, 41))
        self.jhumInRecSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.jhumInRecSubmitButton.setObjectName("jhumInRecSubmitButton")
        self.jhumRec1Spin = QtWidgets.QDoubleSpinBox(self.jhumInRecFrame)
        self.jhumRec1Spin.setGeometry(QtCore.QRect(140, 130, 81, 31))
        self.jhumRec1Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.jhumRec1Spin.setMaximum(999.99)
        self.jhumRec1Spin.setObjectName("jhumRec1Spin")
        self.jhumRec2Spin = QtWidgets.QDoubleSpinBox(self.jhumInRecFrame)
        self.jhumRec2Spin.setGeometry(QtCore.QRect(140, 170, 81, 31))
        self.jhumRec2Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.jhumRec2Spin.setMaximum(999.99)
        self.jhumRec2Spin.setObjectName("jhumRec2Spin")
        self.jhumRec3Spin = QtWidgets.QDoubleSpinBox(self.jhumInRecFrame)
        self.jhumRec3Spin.setGeometry(QtCore.QRect(140, 210, 81, 31))
        self.jhumRec3Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.jhumRec3Spin.setMaximum(999.99)
        self.jhumRec3Spin.setObjectName("jhumRec3Spin")
        self.jhumRec1Label = QtWidgets.QLabel(self.jhumInRecFrame)
        self.jhumRec1Label.setGeometry(QtCore.QRect(50, 140, 71, 21))
        self.jhumRec1Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.jhumRec1Label.setObjectName("jhumRec1Label")
        self.jhumRec2Label = QtWidgets.QLabel(self.jhumInRecFrame)
        self.jhumRec2Label.setGeometry(QtCore.QRect(50, 180, 71, 21))
        self.jhumRec2Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.jhumRec2Label.setObjectName("jhumRec2Label")
        self.jhumRec3Label = QtWidgets.QLabel(self.jhumInRecFrame)
        self.jhumRec3Label.setGeometry(QtCore.QRect(50, 220, 71, 21))
        self.jhumRec3Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.jhumRec3Label.setObjectName("jhumRec3Label")
        self.jhumInRecLevel = QtWidgets.QComboBox(self.jhumInRecFrame)
        self.jhumInRecLevel.setGeometry(QtCore.QRect(40, 70, 221, 41))
        self.jhumInRecLevel.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.jhumInRecLevel.setObjectName("jhumInRecLevel")
        self.jhumInRecLevel.addItem("")
        self.jhumInRecLevel.addItem("")
        self.jhumInRecLevel.addItem("")
        self.jhumHomeButton = QtWidgets.QPushButton(self.jhumanoidHomeTab)
        self.jhumHomeButton.setGeometry(QtCore.QRect(310, 20, 131, 41))
        self.jhumHomeButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.jhumHomeButton.setObjectName("jhumHomeButton")
        self.jhumanoidTab.addTab(self.jhumanoidHomeTab, "")
        self.jhumanoidTeamTab = QtWidgets.QWidget()
        self.jhumanoidTeamTab.setObjectName("jhumanoidTeamTab")
        self.jhumTeamTable = QtWidgets.QTableWidget(self.jhumanoidTeamTab)
        self.jhumTeamTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.jhumTeamTable.setObjectName("jhumTeamTable")
        self.jhumTeamTable.setColumnCount(0)
        self.jhumTeamTable.setRowCount(0)
        self.jhumanoidTab.addTab(self.jhumanoidTeamTab, "")
        self.jhumanoidPreTab = QtWidgets.QWidget()
        self.jhumanoidPreTab.setObjectName("jhumanoidPreTab")
        self.jhumPreTable = QtWidgets.QTableWidget(self.jhumanoidPreTab)
        self.jhumPreTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.jhumPreTable.setObjectName("jhumPreTable")
        self.jhumPreTable.setColumnCount(0)
        self.jhumPreTable.setRowCount(0)
        self.jhumanoidTab.addTab(self.jhumanoidPreTab, "")
        self.jhumanoidSemiTab = QtWidgets.QWidget()
        self.jhumanoidSemiTab.setObjectName("jhumanoidSemiTab")
        self.jhumSemiTable = QtWidgets.QTableWidget(self.jhumanoidSemiTab)
        self.jhumSemiTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.jhumSemiTable.setObjectName("jhumSemiTable")
        self.jhumSemiTable.setColumnCount(0)
        self.jhumSemiTable.setRowCount(0)
        self.jhumanoidTab.addTab(self.jhumanoidSemiTab, "")
        self.jhumanoidFinalTab = QtWidgets.QWidget()
        self.jhumanoidFinalTab.setObjectName("jhumanoidFinalTab")
        self.jhumFinalTable = QtWidgets.QTableWidget(self.jhumanoidFinalTab)
        self.jhumFinalTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.jhumFinalTable.setObjectName("jhumFinalTable")
        self.jhumFinalTable.setColumnCount(0)
        self.jhumFinalTable.setRowCount(0)
        self.jhumanoidTab.addTab(self.jhumanoidFinalTab, "")
        self.jhumanoidTitle = QtWidgets.QLabel(self.jhumanoidPage)
        self.jhumanoidTitle.setGeometry(QtCore.QRect(300, 30, 221, 51))
        self.jhumanoidTitle.setStyleSheet("font: 22pt \"Laksaman\";")
        self.jhumanoidTitle.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.jhumanoidTitle.setObjectName("jhumanoidTitle")
        self.stackedWidget.addWidget(self.jhumanoidPage)
        self.transpoterAPage = QtWidgets.QWidget()
        self.transpoterAPage.setObjectName("transpoterAPage")
        self.transporterATab = QtWidgets.QTabWidget(self.transpoterAPage)
        self.transporterATab.setGeometry(QtCore.QRect(30, 90, 741, 471))
        self.transporterATab.setObjectName("transporterATab")
        self.transporterAHomeTab = QtWidgets.QWidget()
        self.transporterAHomeTab.setEnabled(True)
        self.transporterAHomeTab.setObjectName("transporterAHomeTab")
        self.transporterAHomeButton = QtWidgets.QPushButton(self.transporterAHomeTab)
        self.transporterAHomeButton.setGeometry(QtCore.QRect(310, 20, 131, 41))
        self.transporterAHomeButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.transporterAHomeButton.setObjectName("transporterAHomeButton")
        self.transAInTeamFrame = QtWidgets.QFrame(self.transporterAHomeTab)
        self.transAInTeamFrame.setGeometry(QtCore.QRect(30, 70, 301, 321))
        self.transAInTeamFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.transAInTeamFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transAInTeamFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transAInTeamFrame.setObjectName("transAInTeamFrame")
        self.transAInTeamName = QtWidgets.QLineEdit(self.transAInTeamFrame)
        self.transAInTeamName.setGeometry(QtCore.QRect(40, 50, 221, 41))
        self.transAInTeamName.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transAInTeamName.setObjectName("transAInTeamName")
        self.transAInTeamDep = QtWidgets.QLineEdit(self.transAInTeamFrame)
        self.transAInTeamDep.setGeometry(QtCore.QRect(40, 130, 221, 41))
        self.transAInTeamDep.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transAInTeamDep.setObjectName("transAInTeamDep")
        self.transAInTeamSubmitButton = QtWidgets.QPushButton(self.transAInTeamFrame)
        self.transAInTeamSubmitButton.setGeometry(QtCore.QRect(80, 220, 131, 41))
        self.transAInTeamSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.transAInTeamSubmitButton.setObjectName("transAInTeamSubmitButton")
        self.transAInRecFrame = QtWidgets.QFrame(self.transporterAHomeTab)
        self.transAInRecFrame.setGeometry(QtCore.QRect(410, 70, 301, 321))
        self.transAInRecFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.transAInRecFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transAInRecFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transAInRecFrame.setObjectName("transAInRecFrame")
        self.transAInRecTeam = QtWidgets.QLineEdit(self.transAInRecFrame)
        self.transAInRecTeam.setGeometry(QtCore.QRect(40, 20, 221, 41))
        self.transAInRecTeam.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transAInRecTeam.setObjectName("transAInRecTeam")
        self.transAInRecSubmitButton = QtWidgets.QPushButton(self.transAInRecFrame)
        self.transAInRecSubmitButton.setGeometry(QtCore.QRect(90, 260, 131, 41))
        self.transAInRecSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.transAInRecSubmitButton.setObjectName("transAInRecSubmitButton")
        self.transARec1Spin = QtWidgets.QDoubleSpinBox(self.transAInRecFrame)
        self.transARec1Spin.setGeometry(QtCore.QRect(140, 130, 81, 31))
        self.transARec1Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transARec1Spin.setMaximum(999.99)
        self.transARec1Spin.setObjectName("transARec1Spin")
        self.transARec2Spin = QtWidgets.QDoubleSpinBox(self.transAInRecFrame)
        self.transARec2Spin.setGeometry(QtCore.QRect(140, 170, 81, 31))
        self.transARec2Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transARec2Spin.setMaximum(999.99)
        self.transARec2Spin.setObjectName("transARec2Spin")
        self.transARec3Spin = QtWidgets.QDoubleSpinBox(self.transAInRecFrame)
        self.transARec3Spin.setGeometry(QtCore.QRect(140, 210, 81, 31))
        self.transARec3Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transARec3Spin.setMaximum(999.99)
        self.transARec3Spin.setObjectName("transARec3Spin")
        self.transARec1Label = QtWidgets.QLabel(self.transAInRecFrame)
        self.transARec1Label.setGeometry(QtCore.QRect(50, 140, 71, 21))
        self.transARec1Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transARec1Label.setObjectName("transARec1Label")
        self.transARec2Label = QtWidgets.QLabel(self.transAInRecFrame)
        self.transARec2Label.setGeometry(QtCore.QRect(50, 180, 71, 21))
        self.transARec2Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transARec2Label.setObjectName("transARec2Label")
        self.transARec3Label = QtWidgets.QLabel(self.transAInRecFrame)
        self.transARec3Label.setGeometry(QtCore.QRect(50, 220, 71, 21))
        self.transARec3Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transARec3Label.setObjectName("transARec3Label")
        self.transAInRecLevel = QtWidgets.QComboBox(self.transAInRecFrame)
        self.transAInRecLevel.setGeometry(QtCore.QRect(40, 70, 221, 41))
        self.transAInRecLevel.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transAInRecLevel.setObjectName("transAInRecLevel")
        self.transAInRecLevel.addItem("")
        self.transAInRecLevel.addItem("")
        self.transAInRecLevel.addItem("")
        self.transporterATab.addTab(self.transporterAHomeTab, "")
        self.transporterATeamTab = QtWidgets.QWidget()
        self.transporterATeamTab.setObjectName("transporterATeamTab")
        self.transATeamTable = QtWidgets.QTableWidget(self.transporterATeamTab)
        self.transATeamTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.transATeamTable.setObjectName("transATeamTable")
        self.transATeamTable.setColumnCount(0)
        self.transATeamTable.setRowCount(0)
        self.transporterATab.addTab(self.transporterATeamTab, "")
        self.transporterAPreTab = QtWidgets.QWidget()
        self.transporterAPreTab.setObjectName("transporterAPreTab")
        self.transAPreTable = QtWidgets.QTableWidget(self.transporterAPreTab)
        self.transAPreTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.transAPreTable.setObjectName("transAPreTable")
        self.transAPreTable.setColumnCount(0)
        self.transAPreTable.setRowCount(0)
        self.transporterATab.addTab(self.transporterAPreTab, "")
        self.transporterASemiTab = QtWidgets.QWidget()
        self.transporterASemiTab.setObjectName("transporterASemiTab")
        self.transASemiTable = QtWidgets.QTableWidget(self.transporterASemiTab)
        self.transASemiTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.transASemiTable.setObjectName("transASemiTable")
        self.transASemiTable.setColumnCount(0)
        self.transASemiTable.setRowCount(0)
        self.transporterATab.addTab(self.transporterASemiTab, "")
        self.transporterAFinalTab = QtWidgets.QWidget()
        self.transporterAFinalTab.setObjectName("transporterAFinalTab")
        self.transAFinalTable = QtWidgets.QTableWidget(self.transporterAFinalTab)
        self.transAFinalTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.transAFinalTable.setObjectName("transAFinalTable")
        self.transAFinalTable.setColumnCount(0)
        self.transAFinalTable.setRowCount(0)
        self.transporterATab.addTab(self.transporterAFinalTab, "")
        self.transporterATitle = QtWidgets.QLabel(self.transpoterAPage)
        self.transporterATitle.setGeometry(QtCore.QRect(310, 30, 181, 51))
        self.transporterATitle.setStyleSheet("font: 22pt \"Laksaman\";")
        self.transporterATitle.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.transporterATitle.setObjectName("transporterATitle")
        self.stackedWidget.addWidget(self.transpoterAPage)
        self.transporterBPage = QtWidgets.QWidget()
        self.transporterBPage.setObjectName("transporterBPage")
        self.transporterBTab = QtWidgets.QTabWidget(self.transporterBPage)
        self.transporterBTab.setGeometry(QtCore.QRect(20, 90, 741, 471))
        self.transporterBTab.setObjectName("transporterBTab")
        self.transporterBHomeTab = QtWidgets.QWidget()
        self.transporterBHomeTab.setEnabled(True)
        self.transporterBHomeTab.setObjectName("transporterBHomeTab")
        self.transporterBHomeButton = QtWidgets.QPushButton(self.transporterBHomeTab)
        self.transporterBHomeButton.setGeometry(QtCore.QRect(300, 10, 131, 41))
        self.transporterBHomeButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.transporterBHomeButton.setObjectName("transporterBHomeButton")
        self.transBInRecFrame = QtWidgets.QFrame(self.transporterBHomeTab)
        self.transBInRecFrame.setGeometry(QtCore.QRect(400, 60, 301, 321))
        self.transBInRecFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.transBInRecFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transBInRecFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transBInRecFrame.setObjectName("transBInRecFrame")
        self.transBInRecTeam = QtWidgets.QLineEdit(self.transBInRecFrame)
        self.transBInRecTeam.setGeometry(QtCore.QRect(40, 20, 221, 41))
        self.transBInRecTeam.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transBInRecTeam.setObjectName("transBInRecTeam")
        self.transBInRecSubmitButton = QtWidgets.QPushButton(self.transBInRecFrame)
        self.transBInRecSubmitButton.setGeometry(QtCore.QRect(90, 260, 131, 41))
        self.transBInRecSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.transBInRecSubmitButton.setObjectName("transBInRecSubmitButton")
        self.transBRec1Spin = QtWidgets.QDoubleSpinBox(self.transBInRecFrame)
        self.transBRec1Spin.setGeometry(QtCore.QRect(140, 130, 81, 31))
        self.transBRec1Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transBRec1Spin.setMaximum(999.99)
        self.transBRec1Spin.setObjectName("transBRec1Spin")
        self.transBRec2Spin = QtWidgets.QDoubleSpinBox(self.transBInRecFrame)
        self.transBRec2Spin.setGeometry(QtCore.QRect(140, 170, 81, 31))
        self.transBRec2Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transBRec2Spin.setMaximum(999.99)
        self.transBRec2Spin.setObjectName("transBRec2Spin")
        self.transBRec3Spin = QtWidgets.QDoubleSpinBox(self.transBInRecFrame)
        self.transBRec3Spin.setGeometry(QtCore.QRect(140, 210, 81, 31))
        self.transBRec3Spin.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transBRec3Spin.setMaximum(999.99)
        self.transBRec3Spin.setObjectName("transBRec3Spin")
        self.transBRec1Label = QtWidgets.QLabel(self.transBInRecFrame)
        self.transBRec1Label.setGeometry(QtCore.QRect(50, 140, 71, 21))
        self.transBRec1Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transBRec1Label.setObjectName("transBRec1Label")
        self.transBRec2Label = QtWidgets.QLabel(self.transBInRecFrame)
        self.transBRec2Label.setGeometry(QtCore.QRect(50, 180, 71, 21))
        self.transBRec2Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transBRec2Label.setObjectName("transBRec2Label")
        self.transBRec3Label = QtWidgets.QLabel(self.transBInRecFrame)
        self.transBRec3Label.setGeometry(QtCore.QRect(50, 220, 71, 21))
        self.transBRec3Label.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transBRec3Label.setObjectName("transBRec3Label")
        self.transBInRecLevel = QtWidgets.QComboBox(self.transBInRecFrame)
        self.transBInRecLevel.setGeometry(QtCore.QRect(40, 70, 221, 41))
        self.transBInRecLevel.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transBInRecLevel.setObjectName("transBInRecLevel")
        self.transBInRecLevel.addItem("")
        self.transBInRecLevel.addItem("")
        self.transBInRecLevel.addItem("")
        self.transBInTeamFrame = QtWidgets.QFrame(self.transporterBHomeTab)
        self.transBInTeamFrame.setGeometry(QtCore.QRect(20, 60, 301, 321))
        self.transBInTeamFrame.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.transBInTeamFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transBInTeamFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transBInTeamFrame.setObjectName("transBInTeamFrame")
        self.transBInTeamName = QtWidgets.QLineEdit(self.transBInTeamFrame)
        self.transBInTeamName.setGeometry(QtCore.QRect(40, 50, 221, 41))
        self.transBInTeamName.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transBInTeamName.setObjectName("transBInTeamName")
        self.transBInTeamDep = QtWidgets.QLineEdit(self.transBInTeamFrame)
        self.transBInTeamDep.setGeometry(QtCore.QRect(40, 130, 221, 41))
        self.transBInTeamDep.setStyleSheet("font: 63 11pt \"KacstArt\";")
        self.transBInTeamDep.setObjectName("transBInTeamDep")
        self.transBInTeamSubmitButton = QtWidgets.QPushButton(self.transBInTeamFrame)
        self.transBInTeamSubmitButton.setGeometry(QtCore.QRect(80, 220, 131, 41))
        self.transBInTeamSubmitButton.setStyleSheet("font: 63 14pt \"KacstArt\";")
        self.transBInTeamSubmitButton.setObjectName("transBInTeamSubmitButton")
        self.transporterBTab.addTab(self.transporterBHomeTab, "")
        self.transporterBTeamTab = QtWidgets.QWidget()
        self.transporterBTeamTab.setObjectName("transporterBTeamTab")
        self.transBTeamTable = QtWidgets.QTableWidget(self.transporterBTeamTab)
        self.transBTeamTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.transBTeamTable.setObjectName("transBTeamTable")
        self.transBTeamTable.setColumnCount(0)
        self.transBTeamTable.setRowCount(0)
        self.transporterBTab.addTab(self.transporterBTeamTab, "")
        self.transporterBPreTab = QtWidgets.QWidget()
        self.transporterBPreTab.setObjectName("transporterBPreTab")
        self.transBPreTable = QtWidgets.QTableWidget(self.transporterBPreTab)
        self.transBPreTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.transBPreTable.setObjectName("transBPreTable")
        self.transBPreTable.setColumnCount(0)
        self.transBPreTable.setRowCount(0)
        self.transporterBTab.addTab(self.transporterBPreTab, "")
        self.transporterBSemiTab = QtWidgets.QWidget()
        self.transporterBSemiTab.setObjectName("transporterBSemiTab")
        self.transBSemiTable = QtWidgets.QTableWidget(self.transporterBSemiTab)
        self.transBSemiTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.transBSemiTable.setObjectName("transBSemiTable")
        self.transBSemiTable.setColumnCount(0)
        self.transBSemiTable.setRowCount(0)
        self.transporterBTab.addTab(self.transporterBSemiTab, "")
        self.transporterBFinalTab = QtWidgets.QWidget()
        self.transporterBFinalTab.setObjectName("transporterBFinalTab")
        self.transBFinalTable = QtWidgets.QTableWidget(self.transporterBFinalTab)
        self.transBFinalTable.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.transBFinalTable.setObjectName("transBFinalTable")
        self.transBFinalTable.setColumnCount(0)
        self.transBFinalTable.setRowCount(0)
        self.transporterBTab.addTab(self.transporterBFinalTab, "")
        self.transporterBTitle = QtWidgets.QLabel(self.transporterBPage)
        self.transporterBTitle.setGeometry(QtCore.QRect(300, 30, 191, 51))
        self.transporterBTitle.setStyleSheet("font: 22pt \"Laksaman\";")
        self.transporterBTitle.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.transporterBTitle.setObjectName("transporterBTitle")
        self.stackedWidget.addWidget(self.transporterBPage)
        autMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(autMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        autMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(autMain)
        self.statusbar.setObjectName("statusbar")
        autMain.setStatusBar(self.statusbar)

        self.retranslateUi(autMain)
        self.stackedWidget.setCurrentIndex(0)
        self.humanoidTab.setCurrentIndex(0)
        self.transporterTab.setCurrentIndex(0)
        self.uavTab.setCurrentIndex(0)
        self.deminerTab.setCurrentIndex(0)
        self.atworkTab.setCurrentIndex(0)
        self.jhumanoidTab.setCurrentIndex(0)
        self.transporterATab.setCurrentIndex(0)
        self.transporterBTab.setCurrentIndex(0)

        #MyCode Start
        #League Page Forwards Start
        self.humanoidButton.clicked.connect(lambda: self.forward('humanoid'))
        self.transporterButton.clicked.connect(lambda: self.forward('transporter'))
        self.uavButton.clicked.connect(lambda: self.forward('uav'))
        self.deminerButton.clicked.connect(lambda: self.forward('deminer'))
        self.atworkButton.clicked.connect(lambda: self.forward('at work'))
        self.jhumanoidButton.clicked.connect(lambda: self.forward('junior humanoid'))
        self.transporterAButton.clicked.connect(lambda: self.forward('transporter a'))
        self.transpoterBButton.clicked.connect(lambda: self.forward('transporter b'))

        #League Page Forwards Finished

        #back to home start
        self.humHomeButton.clicked.connect(lambda: self.backward('humanoid'))
        self.transporterHomeButton.clicked.connect(lambda: self.backward('transporter'))
        self.uavHomeButton.clicked.connect(lambda: self.backward('uav'))
        self.deminerHomeButton.clicked.connect(lambda: self.backward('deminer'))
        self.atworkHomeButto.clicked.connect(lambda: self.backward('at work'))
        self.jhumHomeButton.clicked.connect(lambda: self.backward('junior humanoid'))
        self.transporterAHomeButton.clicked.connect(lambda: self.backward('transporter a'))
        self.transporterBHomeButton.clicked.connect(lambda: self.backward('transporter b'))
        #back to home finished

        #insert team start
        self.humInTeamSubmitButton.clicked.connect(lambda: self.insertTeam('humanoid'))
        self.transporterInTeamSubmitButton.clicked.connect(lambda: self.insertTeam('transporter'))
        self.uavInTeamSubmitButton.clicked.connect(lambda: self.insertTeam('uav'))
        self.deminerInTeamSubmitButton.clicked.connect(lambda: self.insertTeam('deminer'))
        self.atworkInTeamSubmitButton.clicked.connect(lambda: self.insertTeam('at work'))
        self.jhumInRecSubmitButton.clicked.connect(lambda: self.insertTeam('junior humanoid'))
        self.transAInTeamSubmitButton.clicked.connect(lambda: self.insertTeam('transporter a'))
        self.transBInTeamSubmitButton.clicked.connect(lambda: self.insertTeam('transporter b'))
        #insert team finish

        #insert record start
        self.humInRecSubmitButton.clicked.connect(lambda: self.insertRecord('humanoid'))
        self.transporterInRecSubmitButton.clicked.connect(lambda: self.insertRecord('transporter'))
        self.uavInRecSubmitButton.clicked.connect(lambda: self.insertRecord('uav'))
        self.deminerInRecSubmitButton.clicked.connect(lambda: self.insertRecord('deminer'))
        self.atworkInRecSubmitButton.clicked.connect(lambda: self.insertRecord('at work'))
        self.jhumInRecSubmitButton.clicked.connect(lambda: self.insertRecord('junior humanoid'))
        self.transAInRecSubmitButton.clicked.connect(lambda: self.insertRecord('transporter a'))
        self.transBInRecSubmitButton.clicked.connect(lambda: self.insertRecord('transporter b'))
        #insert record finish

        #Table Initializing Start
        self.humanoidTeamTable.setColumnCount(2)
        self.humanoidPreTable.setColumnCount(5)
        self.humanoidSemiTable.setColumnCount(5)
        self.humanoidFinalTable.setColumnCount(5)

        self.transporterTeamTable.setColumnCount(2)
        self.transporterPreTable.setColumnCount(5)
        self.transporterSemiTable.setColumnCount(5)
        self.transporterFinalTable.setColumnCount(5)

        self.uavTeamTable.setColumnCount(2)
        self.uavPreTable.setColumnCount(5)
        self.uavSemiTable.setColumnCount(5)
        self.uavFinalTable.setColumnCount(5)

        self.deminerTeamTable.setColumnCount(2)
        self.deminerPreTable.setColumnCount(5)
        self.deminerSemiTable.setColumnCount(5)
        self.deminerFinalTable.setColumnCount(5)

        self.atworkTeamTable.setColumnCount(2)
        self.atworkPreTable.setColumnCount(5)
        self.atworkSemiTable.setColumnCount(5)
        self.atworkFinalTable.setColumnCount(5)

        self.jhumTeamTable.setColumnCount(2)
        self.jhumPreTable.setColumnCount(5)
        self.jhumSemiTable.setColumnCount(5)
        self.jhumFinalTable.setColumnCount(5)

        self.transATeamTable.setColumnCount(2)
        self.transAPreTable.setColumnCount(5)
        self.transASemiTable.setColumnCount(5)
        self.transAFinalTable.setColumnCount(5)

        self.transBTeamTable.setColumnCount(2)
        self.transBPreTable.setColumnCount(5)
        self.transBSemiTable.setColumnCount(5)
        self.transBFinalTable.setColumnCount(5)
        #Table Initializing Finish

        self.updateTeams()
        self.updateResults()
        #My Code Finish

        QtCore.QMetaObject.connectSlotsByName(autMain)

    def forward(self, leagueName):
        if(leagueName == "humanoid"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() +1)
        elif(leagueName == "transporter"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() +2)
        elif(leagueName == "uav"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() +3)
        elif(leagueName == "deminer"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() +4)
        elif(leagueName == "at work"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() +5)
        elif(leagueName == "junior humanoid"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() +6)
        elif(leagueName == "transporter a"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() +7)
        elif(leagueName == "transporter b"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() +8)

    def backward(self, leagueName):
        if(leagueName == "humanoid"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() -1)
            #print(self.humRec1Spin.value())
        elif(leagueName == "transporter"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() -2)
        elif(leagueName == "uav"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() -3)
        elif(leagueName == "deminer"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() -4)
        elif(leagueName == "at work"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() -5)
        elif(leagueName == "junior humanoid"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() -6)
        elif(leagueName == "transporter a"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() -7)
        elif(leagueName == "transporter b"):
            self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() -8)

    def insertTeam(self, leagueName):
        if(leagueName == "humanoid"):
            teamName = self.humInTeamName.text()
            depName = self.humInTeamDep.text()
            mydb.insertTeam(teamName, "Humanoid", depName)
        elif(leagueName == "transporter"):
            teamName = self.transporterInTeamName.text()
            depName = self.transporterInTeamDep.text()
            mydb.insertTeam(teamName, "Transporter", depName)
        elif(leagueName == "uav"):
            teamName = self.uavInTeamName.text()
            depName = self.uavInTeamDep.text()
            mydb.insertTeam(teamName, "UAV", depName)
        elif(leagueName == "deminer"):
            teamName = self.deminerInTeamName.text()
            depName = self.deminerInTeamDep.text()
            mydb.insertTeam(teamName, "Deminer", depName)
        elif(leagueName == "at work"):
            teamName = self.atworkInTeamName.text()
            depName = self.atworkInTeamDep.text()
            mydb.insertTeam(teamName, "@Work", depName)
        elif(leagueName == "junior humanoid"):
            teamName = self.jhumInTeamName.text()
            depName = self.jhumInTeamDep.text()
            mydb.insertTeam(teamName, "Junior Humanoid", depName)
        elif(leagueName == "transporter a"):
            teamName = self.transAInTeamName.text()
            depName = self.transAInTeamDep.text()
            mydb.insertTeam(teamName, "Transporter A", depName)
        elif(leagueName == "transporter b"):
            teamName = self.transBInTeamName.text()
            depName = self.transBInTeamDep.text()
            mydb.insertTeam(teamName, "Transporter B", depName)
        self.updateTeams()

    def insertRecord(self, leagueName):
        if(leagueName == "humanoid"):
            teamName = self.humInRecTeam.text()
            preLevel = str(self.humInRecLevel.currentText())
            recOne = float(self.humRec1Spin.value())
            recTwo = float(self.humRec2Spin.value())
            recThree = float(self.humRec3Spin.value())
            minRec = min(recOne, recTwo, recThree)
            mydb.insertRecord(preLevel, teamName, "Humanoid", recOne, recTwo, recThree, minRec)
        elif(leagueName == "transporter"):
            teamName = self.transporterInRecTeam.text()
            preLevel = str(self.transporterInRecLevel.currentText())
            recOne = self.transporterRec1Spin.value()
            recTwo = self.transporterRec2Spin.value()
            recThree = self.transporterRec3Spin.value()
            minRec = min(recOne, recTwo, recThree)
            mydb.insertRecord(preLevel, teamName, "Transporter", recOne, recTwo, recThree, minRec)
        elif(leagueName == "uav"):
            teamName = self.uavInRecTeam.text()
            preLevel = str(self.uavInRecLevel.currentText())
            recOne = self.uavRec1Spin.value()
            recTwo = self.uavRec2Spin.value()
            recThree = self.uavRec3Spin.value()
            minRec = min(recOne, recTwo, recThree)
            mydb.insertRecord(preLevel, teamName, "UAV", recOne, recTwo, recThree, minRec)
        elif(leagueName == "deminer"):
            teamName = self.deminerInRecTeam.text()
            preLevel = str(self.deminerInRecLevel.currentText())
            recOne = self.deminerRec1Spin.value()
            recTwo = self.deminerRec2Spin.value()
            recThree = self.deminerRec3Spin.value()
            minRec = min(recOne, recTwo, recThree)
            mydb.insertRecord(preLevel, teamName, "Deminer", recOne, recTwo, recThree, minRec)
        elif(leagueName == "at work"):
            teamName = self.atworkInRecTeam.text()
            preLevel = str(self.atworkInRecLevel.currentText())
            recOne = self.atworkRec1Spin.value()
            recTwo = self.atworkRec2Spin.value()
            recThree = self.atworkRec3Spin.value()
            minRec = min(recOne, recTwo, recThree)
            mydb.insertRecord(preLevel, teamName, "@Work", recOne, recTwo, recThree, minRec)
        elif(leagueName == "junior humanoid"):
            teamName = self.jhumInRecTeam.text()
            preLevel = str(self.jhumInRecLevel.currentText())
            recOne = self.jhumRec1Spin.value()
            recTwo = self.jhumRec2Spin.value()
            recThree = self.jhumRec3Spin.value()
            minRec = min(recOne, recTwo, recThree)
            mydb.insertRecord(preLevel, teamName, "Junior Humanoid", recOne, recTwo, recThree, minRec)
        elif(leagueName == "transporter a"):
            teamName = self.transAInRecTeam.text()
            preLevel = str(self.transAInRecLevel.currentText())
            recOne = self.transARec1Spin.value()
            recTwo = self.transARec2Spin.value()
            recThree = self.transARec3Spin.value()
            minRec = min(recOne, recTwo, recThree)
            mydb.insertRecord(preLevel, teamName, "Transporter A", recOne, recTwo, recThree, minRec)
        elif(leagueName == "transporter b"):
            teamName = self.transBInRecTeam.text()
            preLevel = str(self.transBInRecLevel.currentText())
            recOne = self.transBRec1Spin.value()
            recTwo = self.transBRec2Spin.value()
            recThree = self.transBRec3Spin.value()
            minRec = min(recOne, recTwo, recThree)
            mydb.insertRecord(preLevel, teamName, "Transporter B", recOne, recTwo, recThree, minRec)
        self.updateResults()

    def updateTeams(self):

        teams = ["Humanoid", "Transporter", "UAV", "Deminer", "@Work", "Junior Humanoid", "Transporter A", "Transporter B"]
        tables = [self.humanoidTeamTable, self.transporterTeamTable, self.uavTeamTable, self.deminerTeamTable,
                  self.atworkTeamTable, self.jhumTeamTable, self.transATeamTable, self.transBTeamTable]
        for teamCnt in range(len(teams)):
            rows = mydb.getTeams(teams[teamCnt])
            rowsLen = len(rows)
            tables[teamCnt].setRowCount(rowsLen + 1)

            tables[teamCnt].setStyleSheet("font: 63 15pt \"KacstArt\";")
            tables[teamCnt].setItem(0, 0, QTableWidgetItem("Team Name"))
            tables[teamCnt].item(0, 0).setBackground(QtGui.QColor(255, 255, 153))
            tables[teamCnt].setItem(0, 1, QTableWidgetItem("Dependency Name"))
            tables[teamCnt].item(0, 1).setBackground(QtGui.QColor(255, 255, 153))

            for cnt in range(rowsLen):
                #tables[teamCnt].setItem(cnt, 0, rows[cnt][1])
                tables[teamCnt].setItem(cnt + 1, 0, QTableWidgetItem(rows[cnt][1]))
                tables[teamCnt].setItem(cnt + 1, 1, QTableWidgetItem(rows[cnt][2]))
            tables[teamCnt].resizeColumnsToContents()

    def updateResults(self):
        teams = ["Humanoid", "Transporter", "UAV", "Deminer", "@Work", "Junior Humanoid", "Transporter A",
                 "Transporter B"]
        levels = ["Prepration", "Semi Final", "Final"]
        tables = [[self.humanoidPreTable, self.transporterPreTable, self.uavPreTable, self.deminerPreTable,
                  self.atworkPreTable, self.jhumPreTable, self.transAPreTable, self.transBPreTable],
                  [self.humanoidSemiTable, self.transporterSemiTable, self.uavSemiTable, self.deminerSemiTable,
                   self.atworkSemiTable, self.jhumSemiTable, self.transASemiTable, self.transBSemiTable],
                  [self.humanoidFinalTable, self.transporterFinalTable, self.uavFinalTable, self.deminerFinalTable,
                   self.atworkFinalTable, self.jhumFinalTable, self.transAFinalTable, self.transBFinalTable]]

        for teamCnt in range(len(teams)):
            for levelCnt in range(len(levels)):
                rows = mydb.getRecords(teams[teamCnt], levels[levelCnt])
                rowsLen = len(rows)
                tables[levelCnt][teamCnt].setRowCount(rowsLen + 1)

                tables[levelCnt][teamCnt].setStyleSheet("font: 63 15pt \"KacstArt\";")
                tables[levelCnt][teamCnt].setItem(0, 0, QTableWidgetItem("Team Name"))
                tables[levelCnt][teamCnt].item(0, 0).setBackground(QtGui.QColor(255, 255, 153))
                tables[levelCnt][teamCnt].setItem(0, 1, QTableWidgetItem("Rec 1"))
                tables[levelCnt][teamCnt].item(0, 1).setBackground(QtGui.QColor(255, 255, 153))
                tables[levelCnt][teamCnt].setItem(0, 2, QTableWidgetItem("Rec 2"))
                tables[levelCnt][teamCnt].item(0, 2).setBackground(QtGui.QColor(255, 255, 153))
                tables[levelCnt][teamCnt].setItem(0, 3, QTableWidgetItem("Rec 3"))
                tables[levelCnt][teamCnt].item(0, 3).setBackground(QtGui.QColor(255, 255, 153))
                tables[levelCnt][teamCnt].setItem(0, 4, QTableWidgetItem("Best Rec"))
                tables[levelCnt][teamCnt].item(0, 4).setBackground(QtGui.QColor(255, 255, 153))

                for cnt in range(rowsLen):
                    #tables[levelCnt][teamCnt].setItem(cnt, 0, QTableWidgetItem(rows[cnt][1]))
                    tables[levelCnt][teamCnt].setItem(cnt + 1, 0, QTableWidgetItem(rows[cnt][2]))
                    tables[levelCnt][teamCnt].setItem(cnt + 1, 1, QTableWidgetItem(str(rows[cnt][3])))
                    tables[levelCnt][teamCnt].setItem(cnt + 1, 2, QTableWidgetItem(str(rows[cnt][4])))
                    tables[levelCnt][teamCnt].setItem(cnt + 1, 3, QTableWidgetItem(str(rows[cnt][5])))
                    tables[levelCnt][teamCnt].setItem(cnt + 1, 4, QTableWidgetItem(str(rows[cnt][6])))



    def retranslateUi(self, autMain):
        _translate = QtCore.QCoreApplication.translate
        autMain.setWindowTitle(_translate("autMain", "AUT-CUP 2016"))
        self.leagueLabel.setText(_translate("autMain", "Leagues"))
        self.label.setText(_translate("autMain", "Senior"))
        self.humanoidButton.setText(_translate("autMain", "Humanoid"))
        self.transporterButton.setText(_translate("autMain", "Transporter"))
        self.uavButton.setText(_translate("autMain", "UAV"))
        self.deminerButton.setText(_translate("autMain", "Deminer"))
        self.atworkButton.setText(_translate("autMain", "@Work"))
        self.juniorLeague.setText(_translate("autMain", "Junior"))
        self.jhumanoidButton.setText(_translate("autMain", "Humanoid"))
        self.transporterAButton.setText(_translate("autMain", "Transporter A"))
        self.transpoterBButton.setText(_translate("autMain", "Transporter B"))
        self.humanoidTitle.setText(_translate("autMain", "Humanoid"))
        self.humInTeamName.setText(_translate("autMain", "Team Name"))
        self.humInTeamDep.setText(_translate("autMain", "Dependency Name"))
        self.humInTeamSubmitButton.setText(_translate("autMain", "Submit"))
        self.humHomeButton.setText(_translate("autMain", "Home"))
        self.humInRecTeam.setText(_translate("autMain", "Team Name"))
        self.humInRecSubmitButton.setText(_translate("autMain", "Submit"))
        self.humRec1Label.setText(_translate("autMain", "Record 1"))
        self.humRec2Label.setText(_translate("autMain", "Record 2"))
        self.humRec3Label.setText(_translate("autMain", "Record 3"))
        self.humInRecLevel.setItemText(0, _translate("autMain", "Prepration"))
        self.humInRecLevel.setItemText(1, _translate("autMain", "Semi-Final"))
        self.humInRecLevel.setItemText(2, _translate("autMain", "Final"))
        self.humanoidTab.setTabText(self.humanoidTab.indexOf(self.humanoidHomeTab), _translate("autMain", "Home"))
        self.humanoidTab.setTabText(self.humanoidTab.indexOf(self.humanoidTeamTab), _translate("autMain", "Teams"))
        self.humanoidTab.setTabText(self.humanoidTab.indexOf(self.humanoidPreTab), _translate("autMain", "Prepration"))
        self.humanoidTab.setTabText(self.humanoidTab.indexOf(self.humanoidSemiTab), _translate("autMain", "Semi Final"))
        self.humanoidTab.setTabText(self.humanoidTab.indexOf(self.humanoidFinalTab), _translate("autMain", "Final"))
        self.transporterTitle.setText(_translate("autMain", "Transporter"))
        self.transporterInRecTeam.setText(_translate("autMain", "Team Name"))
        self.transporterInRecSubmitButton.setText(_translate("autMain", "Submit"))
        self.transporterRec1Label.setText(_translate("autMain", "Record 1"))
        self.transporterRec2Label.setText(_translate("autMain", "Record 2"))
        self.transporterRec3Label.setText(_translate("autMain", "Record 3"))
        self.transporterInRecLevel.setItemText(0, _translate("autMain", "Prepration"))
        self.transporterInRecLevel.setItemText(1, _translate("autMain", "Semi-Final"))
        self.transporterInRecLevel.setItemText(2, _translate("autMain", "Final"))
        self.transporterHomeButton.setText(_translate("autMain", "Home"))
        self.transporterInTeamName.setText(_translate("autMain", "Team Name"))
        self.transporterInTeamDep.setText(_translate("autMain", "Dependency Name"))
        self.transporterInTeamSubmitButton.setText(_translate("autMain", "Submit"))
        self.transporterTab.setTabText(self.transporterTab.indexOf(self.transporterHomeTab), _translate("autMain", "Home"))
        self.transporterTab.setTabText(self.transporterTab.indexOf(self.transporterTeamTab), _translate("autMain", "Teams"))
        self.transporterTab.setTabText(self.transporterTab.indexOf(self.transporterPreTab), _translate("autMain", "Prepration"))
        self.transporterTab.setTabText(self.transporterTab.indexOf(self.transporterSemiTab), _translate("autMain", "Semi Final"))
        self.transporterTab.setTabText(self.transporterTab.indexOf(self.transporterFinalTab), _translate("autMain", "Final"))
        self.uavTitle.setText(_translate("autMain", "UAV"))
        self.uavHomeButton.setText(_translate("autMain", "Home"))
        self.uavInTeamName.setText(_translate("autMain", "Team Name"))
        self.uavInTeamDep.setText(_translate("autMain", "Dependency Name"))
        self.uavInTeamSubmitButton.setText(_translate("autMain", "Submit"))
        self.uavInRecTeam.setText(_translate("autMain", "Team Name"))
        self.uavInRecSubmitButton.setText(_translate("autMain", "Submit"))
        self.uavRec1Label.setText(_translate("autMain", "Record 1"))
        self.uavRec2Label.setText(_translate("autMain", "Record 2"))
        self.uavRec3Label.setText(_translate("autMain", "Record 3"))
        self.uavInRecLevel.setItemText(0, _translate("autMain", "Prepration"))
        self.uavInRecLevel.setItemText(1, _translate("autMain", "Semi-Final"))
        self.uavInRecLevel.setItemText(2, _translate("autMain", "Final"))
        self.uavTab.setTabText(self.uavTab.indexOf(self.uavHomeTab), _translate("autMain", "Home"))
        self.uavTab.setTabText(self.uavTab.indexOf(self.uavTeamTab), _translate("autMain", "Teams"))
        self.uavTab.setTabText(self.uavTab.indexOf(self.uavPreTab), _translate("autMain", "Prepration"))
        self.uavTab.setTabText(self.uavTab.indexOf(self.uavSemiTab), _translate("autMain", "Semi Final"))
        self.uavTab.setTabText(self.uavTab.indexOf(self.uavFinalTab), _translate("autMain", "Final"))
        self.deminerTitle.setText(_translate("autMain", "Deminer"))
        self.deminerInTeamName.setText(_translate("autMain", "Team Name"))
        self.deminerInTeamDep.setText(_translate("autMain", "Dependency Name"))
        self.deminerInTeamSubmitButton.setText(_translate("autMain", "Submit"))
        self.deminerInRecTeam.setText(_translate("autMain", "Team Name"))
        self.deminerInRecSubmitButton.setText(_translate("autMain", "Submit"))
        self.deminerRec1Label.setText(_translate("autMain", "Record 1"))
        self.deminerRec2Label.setText(_translate("autMain", "Record 2"))
        self.deminerRec3Label.setText(_translate("autMain", "Record 3"))
        self.deminerInRecLevel.setItemText(0, _translate("autMain", "Prepration"))
        self.deminerInRecLevel.setItemText(1, _translate("autMain", "Semi-Final"))
        self.deminerInRecLevel.setItemText(2, _translate("autMain", "Final"))
        self.deminerHomeButton.setText(_translate("autMain", "Home"))
        self.deminerTab.setTabText(self.deminerTab.indexOf(self.deminerHomeTab), _translate("autMain", "Home"))
        self.deminerTab.setTabText(self.deminerTab.indexOf(self.deminerTeamTab), _translate("autMain", "Teams"))
        self.deminerTab.setTabText(self.deminerTab.indexOf(self.deminerPreTab), _translate("autMain", "Prepration"))
        self.deminerTab.setTabText(self.deminerTab.indexOf(self.deminerSemiTab), _translate("autMain", "Semi Final"))
        self.deminerTab.setTabText(self.deminerTab.indexOf(self.deminerFinalTab), _translate("autMain", "Final"))
        self.atworkInTeamName.setText(_translate("autMain", "Team Name"))
        self.atworkInTeamDep.setText(_translate("autMain", "Dependency Name"))
        self.atworkInTeamSubmitButton.setText(_translate("autMain", "Submit"))
        self.atworkInRecTeam.setText(_translate("autMain", "Team Name"))
        self.atworkInRecSubmitButton.setText(_translate("autMain", "Submit"))
        self.atworkRec1Label.setText(_translate("autMain", "Record 1"))
        self.atworkRec2Label.setText(_translate("autMain", "Record 2"))
        self.atworkRec3Label.setText(_translate("autMain", "Record 3"))
        self.atworkInRecLevel.setItemText(0, _translate("autMain", "Prepration"))
        self.atworkInRecLevel.setItemText(1, _translate("autMain", "Semi-Final"))
        self.atworkInRecLevel.setItemText(2, _translate("autMain", "Final"))
        self.atworkHomeButto.setText(_translate("autMain", "Home"))
        self.atworkTab.setTabText(self.atworkTab.indexOf(self.atworkHomeTab), _translate("autMain", "Home"))
        self.atworkTab.setTabText(self.atworkTab.indexOf(self.atworkTeamTab), _translate("autMain", "Teams"))
        self.atworkTab.setTabText(self.atworkTab.indexOf(self.atworkPreTab), _translate("autMain", "Prepration"))
        self.atworkTab.setTabText(self.atworkTab.indexOf(self.atworkSemiTab), _translate("autMain", "Semi Final"))
        self.atworkTab.setTabText(self.atworkTab.indexOf(self.atworkFinalTab), _translate("autMain", "Final"))
        self.atWorkTitle.setText(_translate("autMain", "@Work"))
        self.jhumInTeamName.setText(_translate("autMain", "Team Name"))
        self.jhumInTeamDep.setText(_translate("autMain", "Dependency Name"))
        self.jhumInTeamSubmitButton.setText(_translate("autMain", "Submit"))
        self.jhumInRecTeam.setText(_translate("autMain", "Team Name"))
        self.jhumInRecSubmitButton.setText(_translate("autMain", "Submit"))
        self.jhumRec1Label.setText(_translate("autMain", "Record 1"))
        self.jhumRec2Label.setText(_translate("autMain", "Record 2"))
        self.jhumRec3Label.setText(_translate("autMain", "Record 3"))
        self.jhumInRecLevel.setItemText(0, _translate("autMain", "Prepration"))
        self.jhumInRecLevel.setItemText(1, _translate("autMain", "Semi-Final"))
        self.jhumInRecLevel.setItemText(2, _translate("autMain", "Final"))
        self.jhumHomeButton.setText(_translate("autMain", "Home"))
        self.jhumanoidTab.setTabText(self.jhumanoidTab.indexOf(self.jhumanoidHomeTab), _translate("autMain", "Home"))
        self.jhumanoidTab.setTabText(self.jhumanoidTab.indexOf(self.jhumanoidTeamTab), _translate("autMain", "Teams"))
        self.jhumanoidTab.setTabText(self.jhumanoidTab.indexOf(self.jhumanoidPreTab), _translate("autMain", "Prepration"))
        self.jhumanoidTab.setTabText(self.jhumanoidTab.indexOf(self.jhumanoidSemiTab), _translate("autMain", "Semi Final"))
        self.jhumanoidTab.setTabText(self.jhumanoidTab.indexOf(self.jhumanoidFinalTab), _translate("autMain", "Final"))
        self.jhumanoidTitle.setText(_translate("autMain", "Junior Humanoid"))
        self.transporterAHomeButton.setText(_translate("autMain", "Home"))
        self.transAInTeamName.setText(_translate("autMain", "Team Name"))
        self.transAInTeamDep.setText(_translate("autMain", "Dependency Name"))
        self.transAInTeamSubmitButton.setText(_translate("autMain", "Submit"))
        self.transAInRecTeam.setText(_translate("autMain", "Team Name"))
        self.transAInRecSubmitButton.setText(_translate("autMain", "Submit"))
        self.transARec1Label.setText(_translate("autMain", "Record 1"))
        self.transARec2Label.setText(_translate("autMain", "Record 2"))
        self.transARec3Label.setText(_translate("autMain", "Record 3"))
        self.transAInRecLevel.setItemText(0, _translate("autMain", "Prepration"))
        self.transAInRecLevel.setItemText(1, _translate("autMain", "Semi-Final"))
        self.transAInRecLevel.setItemText(2, _translate("autMain", "Final"))
        self.transporterATab.setTabText(self.transporterATab.indexOf(self.transporterAHomeTab), _translate("autMain", "Home"))
        self.transporterATab.setTabText(self.transporterATab.indexOf(self.transporterATeamTab), _translate("autMain", "Teams"))
        self.transporterATab.setTabText(self.transporterATab.indexOf(self.transporterAPreTab), _translate("autMain", "Prepration"))
        self.transporterATab.setTabText(self.transporterATab.indexOf(self.transporterASemiTab), _translate("autMain", "Semi Final"))
        self.transporterATab.setTabText(self.transporterATab.indexOf(self.transporterAFinalTab), _translate("autMain", "Final"))
        self.transporterATitle.setText(_translate("autMain", "Transporter A"))
        self.transporterBHomeButton.setText(_translate("autMain", "Home"))
        self.transBInRecTeam.setText(_translate("autMain", "Team Name"))
        self.transBInRecSubmitButton.setText(_translate("autMain", "Submit"))
        self.transBRec1Label.setText(_translate("autMain", "Record 1"))
        self.transBRec2Label.setText(_translate("autMain", "Record 2"))
        self.transBRec3Label.setText(_translate("autMain", "Record 3"))
        self.transBInRecLevel.setItemText(0, _translate("autMain", "Prepration"))
        self.transBInRecLevel.setItemText(1, _translate("autMain", "Semi-Final"))
        self.transBInRecLevel.setItemText(2, _translate("autMain", "Final"))
        self.transBInTeamName.setText(_translate("autMain", "Team Name"))
        self.transBInTeamDep.setText(_translate("autMain", "Dependency Name"))
        self.transBInTeamSubmitButton.setText(_translate("autMain", "Submit"))
        self.transporterBTab.setTabText(self.transporterBTab.indexOf(self.transporterBHomeTab), _translate("autMain", "Home"))
        self.transporterBTab.setTabText(self.transporterBTab.indexOf(self.transporterBTeamTab), _translate("autMain", "Teams"))
        self.transporterBTab.setTabText(self.transporterBTab.indexOf(self.transporterBPreTab), _translate("autMain", "Prepration"))
        self.transporterBTab.setTabText(self.transporterBTab.indexOf(self.transporterBSemiTab), _translate("autMain", "Semi Final"))
        self.transporterBTab.setTabText(self.transporterBTab.indexOf(self.transporterBFinalTab), _translate("autMain", "Final"))
        self.transporterBTitle.setText(_translate("autMain", "Transporter B"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    autMain = QtWidgets.QMainWindow()
    ui = Ui_autMain()
    ui.setupUi(autMain)
    autMain.show()
    sys.exit(app.exec_())

